// Readable country names keyed by IOC / WFDF 3-letter code, for labelling WFDF
// entries in the profile-icon picker. Covers the same codes mapped in
// country-flags.ts (only those that resolve to a real flag are shown in the
// picker). Add new codes here alongside country-flags.ts as events are ingested.

export const WFDF_COUNTRY_NAMES: Record<string, string> = {
  ARG: 'Argentina',
  AUS: 'Australia',
  AUT: 'Austria',
  BEL: 'Belgium',
  BRU: 'Brunei',
  CAN: 'Canada',
  CHI: 'Chile',
  CHN: 'China',
  COD: 'DR Congo',
  COL: 'Colombia',
  COS: 'Costa Rica',
  CZE: 'Czechia',
  DEN: 'Denmark',
  DOM: 'Dominican Republic',
  EGY: 'Egypt',
  ESP: 'Spain',
  EST: 'Estonia',
  FIN: 'Finland',
  FRA: 'France',
  GBR: 'Great Britain',
  GER: 'Germany',
  GUA: 'Guatemala',
  GUM: 'Guam',
  HKG: 'Hong Kong',
  HON: 'Honduras',
  HUN: 'Hungary',
  INA: 'Indonesia',
  IND: 'India',
  IRL: 'Ireland',
  ISR: 'Israel',
  ITA: 'Italy',
  JPN: 'Japan',
  KEN: 'Kenya',
  KOR: 'South Korea',
  KUW: 'Kuwait',
  LAT: 'Latvia',
  LBN: 'Lebanon',
  LTU: 'Lithuania',
  MAL: 'Mali',
  MAS: 'Malaysia',
  MEX: 'Mexico',
  NED: 'Netherlands',
  NGR: 'Nigeria',
  NZL: 'New Zealand',
  PAN: 'Panama',
  PEO: 'Peru',
  PHI: 'Philippines',
  POL: 'Poland',
  POR: 'Portugal',
  QAT: 'Qatar',
  RSA: 'South Africa',
  SGP: 'Singapore',
  SUI: 'Switzerland',
  SVK: 'Slovakia',
  SWE: 'Sweden',
  TAN: 'Tanzania',
  THA: 'Thailand',
  TPE: 'Chinese Taipei',
  TUR: 'Türkiye',
  UAE: 'United Arab Emirates',
  UGA: 'Uganda',
  UKR: 'Ukraine',
  URU: 'Uruguay',
  USA: 'United States',
  VEN: 'Venezuela',
  VIR: 'US Virgin Islands',
};
